version: "3.2"
services:
  db: 
    image: postgres
    container_name: db 
    network_mode: host 
    build: . 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=world
